vqa_node:
  ros__parameters:

    questions: ['What is this place?',     
                'What object do you see?',
                'What is to the right of to the *?',
                'What is the material of *?',
                'What is to the shape of *?']
 
    frequency_execution_time: 2.5

