vqa_node:
  ros__parameters:

    questions: ['What object do you see?',
                'Is there a white board?',
                'Is there a fire extinguisher',
                'Is there a door',
                'Is there a brown wall?',
                'Is there a chair?',
                'Is there a trash can']

